### PR TITLE
Deprecate UpdateUser, UpdateGroup and Enterprise

### PR DESCRIPTION
**Pull request by wallner**
Add the `@Deprecated` annotation to the classses `UpdateUser`, `UpdateGroup` and `Enterprise`. We consider them deprecated and want to delete them in the near future.

### CODE REVIEW

**Comment by dacrome** [comment]
Are you sure this is the right change?

**Comment by wallner** [comment]
At least this is what we agreed on. What is the problem you are seeing?

**Comment by dacrome** [comment]
> What is the problem you are seeing?

The change don't fit with the PR title, I guess

**Comment by wallner** [comment]
D'oh! Stupid me!

**Pull request closed without merging**
